#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShopNow")]
public partial class ShopNowDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCPU(CPU instance);
  partial void UpdateCPU(CPU instance);
  partial void DeleteCPU(CPU instance);
  partial void InsertFeedback(Feedback instance);
  partial void UpdateFeedback(Feedback instance);
  partial void DeleteFeedback(Feedback instance);
  partial void InsertHardDrive(HardDrive instance);
  partial void UpdateHardDrive(HardDrive instance);
  partial void DeleteHardDrive(HardDrive instance);
  partial void InsertMonitor(Monitor instance);
  partial void UpdateMonitor(Monitor instance);
  partial void DeleteMonitor(Monitor instance);
  partial void InsertOrder(Order instance);
  partial void UpdateOrder(Order instance);
  partial void DeleteOrder(Order instance);
  partial void InsertO(O instance);
  partial void UpdateO(O instance);
  partial void DeleteO(O instance);
  partial void InsertRAM(RAM instance);
  partial void UpdateRAM(RAM instance);
  partial void DeleteRAM(RAM instance);
  partial void InsertSoundCard(SoundCard instance);
  partial void UpdateSoundCard(SoundCard instance);
  partial void DeleteSoundCard(SoundCard instance);
  partial void Insertuser(user instance);
  partial void Updateuser(user instance);
  partial void Deleteuser(user instance);
  #endregion
	
	public ShopNowDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ShopNowConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ShopNowDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShopNowDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShopNowDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShopNowDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<CPU> CPUs
	{
		get
		{
			return this.GetTable<CPU>();
		}
	}
	
	public System.Data.Linq.Table<Feedback> Feedbacks
	{
		get
		{
			return this.GetTable<Feedback>();
		}
	}
	
	public System.Data.Linq.Table<HardDrive> HardDrives
	{
		get
		{
			return this.GetTable<HardDrive>();
		}
	}
	
	public System.Data.Linq.Table<Monitor> Monitors
	{
		get
		{
			return this.GetTable<Monitor>();
		}
	}
	
	public System.Data.Linq.Table<Order> Orders
	{
		get
		{
			return this.GetTable<Order>();
		}
	}
	
	public System.Data.Linq.Table<O> Os
	{
		get
		{
			return this.GetTable<O>();
		}
	}
	
	public System.Data.Linq.Table<PreMade> PreMades
	{
		get
		{
			return this.GetTable<PreMade>();
		}
	}
	
	public System.Data.Linq.Table<privatesecurity> privatesecurities
	{
		get
		{
			return this.GetTable<privatesecurity>();
		}
	}
	
	public System.Data.Linq.Table<RAM> RAMs
	{
		get
		{
			return this.GetTable<RAM>();
		}
	}
	
	public System.Data.Linq.Table<SoundCard> SoundCards
	{
		get
		{
			return this.GetTable<SoundCard>();
		}
	}
	
	public System.Data.Linq.Table<user> users
	{
		get
		{
			return this.GetTable<user>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CPU")]
public partial class CPU : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Name;
	
	private string _Cost;
	
	private EntitySet<Order> _Orders;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCostChanging(string value);
    partial void OnCostChanged();
    #endregion
	
	public CPU()
	{
		this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this.OnCostChanging(value);
				this.SendPropertyChanging();
				this._Cost = value;
				this.SendPropertyChanged("Cost");
				this.OnCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CPU_Order", Storage="_Orders", ThisKey="ID", OtherKey="CPU_ID")]
	public EntitySet<Order> Orders
	{
		get
		{
			return this._Orders;
		}
		set
		{
			this._Orders.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.CPU = this;
	}
	
	private void detach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.CPU = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Feedback")]
public partial class Feedback : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _User_Feedback;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_FeedbackChanging(string value);
    partial void OnUser_FeedbackChanged();
    #endregion
	
	public Feedback()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Feedback", DbType="VarChar(300) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string User_Feedback
	{
		get
		{
			return this._User_Feedback;
		}
		set
		{
			if ((this._User_Feedback != value))
			{
				this.OnUser_FeedbackChanging(value);
				this.SendPropertyChanging();
				this._User_Feedback = value;
				this.SendPropertyChanged("User_Feedback");
				this.OnUser_FeedbackChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HardDrive")]
public partial class HardDrive : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Name;
	
	private string _Cost;
	
	private EntitySet<Order> _Orders;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCostChanging(string value);
    partial void OnCostChanged();
    #endregion
	
	public HardDrive()
	{
		this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this.OnCostChanging(value);
				this.SendPropertyChanging();
				this._Cost = value;
				this.SendPropertyChanged("Cost");
				this.OnCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HardDrive_Order", Storage="_Orders", ThisKey="ID", OtherKey="HardDrive_ID")]
	public EntitySet<Order> Orders
	{
		get
		{
			return this._Orders;
		}
		set
		{
			this._Orders.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.HardDrive = this;
	}
	
	private void detach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.HardDrive = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Monitor")]
public partial class Monitor : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Name;
	
	private string _Cost;
	
	private EntitySet<Order> _Orders;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCostChanging(string value);
    partial void OnCostChanged();
    #endregion
	
	public Monitor()
	{
		this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this.OnCostChanging(value);
				this.SendPropertyChanging();
				this._Cost = value;
				this.SendPropertyChanged("Cost");
				this.OnCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Monitor_Order", Storage="_Orders", ThisKey="ID", OtherKey="Monitor_ID")]
	public EntitySet<Order> Orders
	{
		get
		{
			return this._Orders;
		}
		set
		{
			this._Orders.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.Monitor = this;
	}
	
	private void detach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.Monitor = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Orders")]
public partial class Order : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _Order_ID;
	
	private System.Guid _InternalComp_ID;
	
	private int _OS_ID;
	
	private int _CPU_ID;
	
	private int _RAM_ID;
	
	private int _HardDrive_ID;
	
	private int _Monitor_ID;
	
	private int _SoundCard_ID;
	
	private string _Cost;
	
	private string _Username;
	
	private EntityRef<CPU> _CPU;
	
	private EntityRef<HardDrive> _HardDrive;
	
	private EntityRef<Monitor> _Monitor;
	
	private EntityRef<O> _O;
	
	private EntityRef<RAM> _RAM;
	
	private EntityRef<SoundCard> _SoundCard;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrder_IDChanging(System.Guid value);
    partial void OnOrder_IDChanged();
    partial void OnInternalComp_IDChanging(System.Guid value);
    partial void OnInternalComp_IDChanged();
    partial void OnOS_IDChanging(int value);
    partial void OnOS_IDChanged();
    partial void OnCPU_IDChanging(int value);
    partial void OnCPU_IDChanged();
    partial void OnRAM_IDChanging(int value);
    partial void OnRAM_IDChanged();
    partial void OnHardDrive_IDChanging(int value);
    partial void OnHardDrive_IDChanged();
    partial void OnMonitor_IDChanging(int value);
    partial void OnMonitor_IDChanged();
    partial void OnSoundCard_IDChanging(int value);
    partial void OnSoundCard_IDChanged();
    partial void OnCostChanging(string value);
    partial void OnCostChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    #endregion
	
	public Order()
	{
		this._CPU = default(EntityRef<CPU>);
		this._HardDrive = default(EntityRef<HardDrive>);
		this._Monitor = default(EntityRef<Monitor>);
		this._O = default(EntityRef<O>);
		this._RAM = default(EntityRef<RAM>);
		this._SoundCard = default(EntityRef<SoundCard>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid Order_ID
	{
		get
		{
			return this._Order_ID;
		}
		set
		{
			if ((this._Order_ID != value))
			{
				this.OnOrder_IDChanging(value);
				this.SendPropertyChanging();
				this._Order_ID = value;
				this.SendPropertyChanged("Order_ID");
				this.OnOrder_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalComp_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid InternalComp_ID
	{
		get
		{
			return this._InternalComp_ID;
		}
		set
		{
			if ((this._InternalComp_ID != value))
			{
				this.OnInternalComp_IDChanging(value);
				this.SendPropertyChanging();
				this._InternalComp_ID = value;
				this.SendPropertyChanged("InternalComp_ID");
				this.OnInternalComp_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OS_ID", DbType="Int NOT NULL")]
	public int OS_ID
	{
		get
		{
			return this._OS_ID;
		}
		set
		{
			if ((this._OS_ID != value))
			{
				if (this._O.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnOS_IDChanging(value);
				this.SendPropertyChanging();
				this._OS_ID = value;
				this.SendPropertyChanged("OS_ID");
				this.OnOS_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPU_ID", DbType="Int NOT NULL")]
	public int CPU_ID
	{
		get
		{
			return this._CPU_ID;
		}
		set
		{
			if ((this._CPU_ID != value))
			{
				if (this._CPU.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnCPU_IDChanging(value);
				this.SendPropertyChanging();
				this._CPU_ID = value;
				this.SendPropertyChanged("CPU_ID");
				this.OnCPU_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAM_ID", DbType="Int NOT NULL")]
	public int RAM_ID
	{
		get
		{
			return this._RAM_ID;
		}
		set
		{
			if ((this._RAM_ID != value))
			{
				if (this._RAM.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnRAM_IDChanging(value);
				this.SendPropertyChanging();
				this._RAM_ID = value;
				this.SendPropertyChanged("RAM_ID");
				this.OnRAM_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HardDrive_ID", DbType="Int NOT NULL")]
	public int HardDrive_ID
	{
		get
		{
			return this._HardDrive_ID;
		}
		set
		{
			if ((this._HardDrive_ID != value))
			{
				if (this._HardDrive.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnHardDrive_IDChanging(value);
				this.SendPropertyChanging();
				this._HardDrive_ID = value;
				this.SendPropertyChanged("HardDrive_ID");
				this.OnHardDrive_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monitor_ID", DbType="Int NOT NULL")]
	public int Monitor_ID
	{
		get
		{
			return this._Monitor_ID;
		}
		set
		{
			if ((this._Monitor_ID != value))
			{
				if (this._Monitor.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMonitor_IDChanging(value);
				this.SendPropertyChanging();
				this._Monitor_ID = value;
				this.SendPropertyChanged("Monitor_ID");
				this.OnMonitor_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoundCard_ID", DbType="Int NOT NULL")]
	public int SoundCard_ID
	{
		get
		{
			return this._SoundCard_ID;
		}
		set
		{
			if ((this._SoundCard_ID != value))
			{
				if (this._SoundCard.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnSoundCard_IDChanging(value);
				this.SendPropertyChanging();
				this._SoundCard_ID = value;
				this.SendPropertyChanged("SoundCard_ID");
				this.OnSoundCard_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this.OnCostChanging(value);
				this.SendPropertyChanging();
				this._Cost = value;
				this.SendPropertyChanged("Cost");
				this.OnCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Username
	{
		get
		{
			return this._Username;
		}
		set
		{
			if ((this._Username != value))
			{
				this.OnUsernameChanging(value);
				this.SendPropertyChanging();
				this._Username = value;
				this.SendPropertyChanged("Username");
				this.OnUsernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CPU_Order", Storage="_CPU", ThisKey="CPU_ID", OtherKey="ID", IsForeignKey=true)]
	public CPU CPU
	{
		get
		{
			return this._CPU.Entity;
		}
		set
		{
			CPU previousValue = this._CPU.Entity;
			if (((previousValue != value) 
						|| (this._CPU.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._CPU.Entity = null;
					previousValue.Orders.Remove(this);
				}
				this._CPU.Entity = value;
				if ((value != null))
				{
					value.Orders.Add(this);
					this._CPU_ID = value.ID;
				}
				else
				{
					this._CPU_ID = default(int);
				}
				this.SendPropertyChanged("CPU");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HardDrive_Order", Storage="_HardDrive", ThisKey="HardDrive_ID", OtherKey="ID", IsForeignKey=true)]
	public HardDrive HardDrive
	{
		get
		{
			return this._HardDrive.Entity;
		}
		set
		{
			HardDrive previousValue = this._HardDrive.Entity;
			if (((previousValue != value) 
						|| (this._HardDrive.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._HardDrive.Entity = null;
					previousValue.Orders.Remove(this);
				}
				this._HardDrive.Entity = value;
				if ((value != null))
				{
					value.Orders.Add(this);
					this._HardDrive_ID = value.ID;
				}
				else
				{
					this._HardDrive_ID = default(int);
				}
				this.SendPropertyChanged("HardDrive");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Monitor_Order", Storage="_Monitor", ThisKey="Monitor_ID", OtherKey="ID", IsForeignKey=true)]
	public Monitor Monitor
	{
		get
		{
			return this._Monitor.Entity;
		}
		set
		{
			Monitor previousValue = this._Monitor.Entity;
			if (((previousValue != value) 
						|| (this._Monitor.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Monitor.Entity = null;
					previousValue.Orders.Remove(this);
				}
				this._Monitor.Entity = value;
				if ((value != null))
				{
					value.Orders.Add(this);
					this._Monitor_ID = value.ID;
				}
				else
				{
					this._Monitor_ID = default(int);
				}
				this.SendPropertyChanged("Monitor");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="O_Order", Storage="_O", ThisKey="OS_ID", OtherKey="ID", IsForeignKey=true)]
	public O O
	{
		get
		{
			return this._O.Entity;
		}
		set
		{
			O previousValue = this._O.Entity;
			if (((previousValue != value) 
						|| (this._O.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._O.Entity = null;
					previousValue.Orders.Remove(this);
				}
				this._O.Entity = value;
				if ((value != null))
				{
					value.Orders.Add(this);
					this._OS_ID = value.ID;
				}
				else
				{
					this._OS_ID = default(int);
				}
				this.SendPropertyChanged("O");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RAM_Order", Storage="_RAM", ThisKey="RAM_ID", OtherKey="ID", IsForeignKey=true)]
	public RAM RAM
	{
		get
		{
			return this._RAM.Entity;
		}
		set
		{
			RAM previousValue = this._RAM.Entity;
			if (((previousValue != value) 
						|| (this._RAM.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._RAM.Entity = null;
					previousValue.Orders.Remove(this);
				}
				this._RAM.Entity = value;
				if ((value != null))
				{
					value.Orders.Add(this);
					this._RAM_ID = value.ID;
				}
				else
				{
					this._RAM_ID = default(int);
				}
				this.SendPropertyChanged("RAM");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SoundCard_Order", Storage="_SoundCard", ThisKey="SoundCard_ID", OtherKey="ID", IsForeignKey=true)]
	public SoundCard SoundCard
	{
		get
		{
			return this._SoundCard.Entity;
		}
		set
		{
			SoundCard previousValue = this._SoundCard.Entity;
			if (((previousValue != value) 
						|| (this._SoundCard.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._SoundCard.Entity = null;
					previousValue.Orders.Remove(this);
				}
				this._SoundCard.Entity = value;
				if ((value != null))
				{
					value.Orders.Add(this);
					this._SoundCard_ID = value.ID;
				}
				else
				{
					this._SoundCard_ID = default(int);
				}
				this.SendPropertyChanged("SoundCard");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OS")]
public partial class O : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Name;
	
	private string _Cost;
	
	private EntitySet<Order> _Orders;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCostChanging(string value);
    partial void OnCostChanged();
    #endregion
	
	public O()
	{
		this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this.OnCostChanging(value);
				this.SendPropertyChanging();
				this._Cost = value;
				this.SendPropertyChanged("Cost");
				this.OnCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="O_Order", Storage="_Orders", ThisKey="ID", OtherKey="OS_ID")]
	public EntitySet<Order> Orders
	{
		get
		{
			return this._Orders;
		}
		set
		{
			this._Orders.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.O = this;
	}
	
	private void detach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.O = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PreMade")]
public partial class PreMade
{
	
	private int _Premade_ID;
	
	private int _OS_ID;
	
	private int _CPU_ID;
	
	private int _RAM_ID;
	
	private int _HardDrive_ID;
	
	private int _Monitor_ID;
	
	private int _SoundCard_ID;
	
	private string _Name;
	
	private string _Cost;
	
	public PreMade()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Premade_ID", DbType="Int NOT NULL")]
	public int Premade_ID
	{
		get
		{
			return this._Premade_ID;
		}
		set
		{
			if ((this._Premade_ID != value))
			{
				this._Premade_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OS_ID", DbType="Int NOT NULL")]
	public int OS_ID
	{
		get
		{
			return this._OS_ID;
		}
		set
		{
			if ((this._OS_ID != value))
			{
				this._OS_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPU_ID", DbType="Int NOT NULL")]
	public int CPU_ID
	{
		get
		{
			return this._CPU_ID;
		}
		set
		{
			if ((this._CPU_ID != value))
			{
				this._CPU_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAM_ID", DbType="Int NOT NULL")]
	public int RAM_ID
	{
		get
		{
			return this._RAM_ID;
		}
		set
		{
			if ((this._RAM_ID != value))
			{
				this._RAM_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HardDrive_ID", DbType="Int NOT NULL")]
	public int HardDrive_ID
	{
		get
		{
			return this._HardDrive_ID;
		}
		set
		{
			if ((this._HardDrive_ID != value))
			{
				this._HardDrive_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monitor_ID", DbType="Int NOT NULL")]
	public int Monitor_ID
	{
		get
		{
			return this._Monitor_ID;
		}
		set
		{
			if ((this._Monitor_ID != value))
			{
				this._Monitor_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoundCard_ID", DbType="Int NOT NULL")]
	public int SoundCard_ID
	{
		get
		{
			return this._SoundCard_ID;
		}
		set
		{
			if ((this._SoundCard_ID != value))
			{
				this._SoundCard_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this._Cost = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.privatesecurity")]
public partial class privatesecurity
{
	
	private string _Email;
	
	private string _SecurityQuestion;
	
	private string _SecurityAnswer;
	
	public privatesecurity()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey = true)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityQuestion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string SecurityQuestion
	{
		get
		{
			return this._SecurityQuestion;
		}
		set
		{
			if ((this._SecurityQuestion != value))
			{
				this._SecurityQuestion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityAnswer", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string SecurityAnswer
	{
		get
		{
			return this._SecurityAnswer;
		}
		set
		{
			if ((this._SecurityAnswer != value))
			{
				this._SecurityAnswer = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RAM")]
public partial class RAM : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Name;
	
	private string _Cost;
	
	private EntitySet<Order> _Orders;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCostChanging(string value);
    partial void OnCostChanged();
    #endregion
	
	public RAM()
	{
		this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this.OnCostChanging(value);
				this.SendPropertyChanging();
				this._Cost = value;
				this.SendPropertyChanged("Cost");
				this.OnCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RAM_Order", Storage="_Orders", ThisKey="ID", OtherKey="RAM_ID")]
	public EntitySet<Order> Orders
	{
		get
		{
			return this._Orders;
		}
		set
		{
			this._Orders.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.RAM = this;
	}
	
	private void detach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.RAM = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoundCard")]
public partial class SoundCard : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Name;
	
	private string _Cost;
	
	private EntitySet<Order> _Orders;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCostChanging(string value);
    partial void OnCostChanged();
    #endregion
	
	public SoundCard()
	{
		this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this.OnCostChanging(value);
				this.SendPropertyChanging();
				this._Cost = value;
				this.SendPropertyChanged("Cost");
				this.OnCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SoundCard_Order", Storage="_Orders", ThisKey="ID", OtherKey="SoundCard_ID")]
	public EntitySet<Order> Orders
	{
		get
		{
			return this._Orders;
		}
		set
		{
			this._Orders.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.SoundCard = this;
	}
	
	private void detach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.SoundCard = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Username;
	
	private string _Password;
	
	private string _Email;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
	
	public user()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Username
	{
		get
		{
			return this._Username;
		}
		set
		{
			if ((this._Username != value))
			{
				this.OnUsernameChanging(value);
				this.SendPropertyChanging();
				this._Username = value;
				this.SendPropertyChanged("Username");
				this.OnUsernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
